djangoOsvobojeniy/djangoOsvobojeniy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('medicine.urls')),

]

djangoOsvobojeniy/medicine/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name="home"),
    path('info/<int:pk>', views.PacientInfoDetailView.as_view(), name="pacient-detail"),
    path('create', views.create, name="New-pacient"),
    path('info/<int:pk>/edit', views.update, name="pacient-update"),
    path('info/<int:pk>/delete', views.delete, name="pacient-delete"),
]

djangoOsvobojeniy/medicine/models.py
from django.db import models


class Pacient(models.Model):
    NamePac = models.CharField("Имя пациента", max_length=70)
    Policy = models.CharField("Номер полиса", max_length=16)
    Birth = models.CharField("Дата рождения",max_length=10)
    Location = models.CharField("Адресс проживания", max_length=70)

    def __str__(self):
        return self.NamePac

    class Meta:
        verbose_name = "Пациент"
        verbose_name_plural = "Пациенты"


class Diagnosis(models.Model):
    Diagnos = models.CharField("Диангоз", max_length=70)
    Severity = models.IntegerField("Степень тяжести")
    diag_policy = models.ForeignKey('Pacient', on_delete=models.CASCADE, blank=True, null=True, verbose_name='Номер полиса')

    def __str__(self):
        return self.Diagnos

    class Meta:
        verbose_name = "Диагноз"
        verbose_name_plural = "Диагнозы"


class Treatment(models.Model):
    MethodOfThreatment = models.CharField("Метод лечения", max_length=70)
    DurationOfTreat = models.CharField("Время лечения", max_length=70)
    treat_policy = models.ForeignKey('Pacient', on_delete=models.CASCADE, blank=True, null=True, verbose_name='Номер полиса')

    def __str__(self):
        return self.MethodOfThreatment

    class Meta:
        verbose_name = "Лечение"
        verbose_name_plural = "Способы лечения"

djangoOsvobojeniy/medicine/forms.py
from .models import *
from django.forms import ModelForm, TextInput, DateInput


class PacientForm(ModelForm):
    class Meta:
        model = Pacient
        fields = ['NamePac', 'Policy', 'Birth', 'Location']

        widgets = {
            'NamePac': TextInput(attrs={
                'class': 'contnent__elem',
                'placeholder': 'ФИО'
            }),
            'Policy': TextInput(attrs={
                'class': 'contnent__elem',
                'placeholder': 'Номер страхового полиса',
            }),
            'Birth': DateInput(attrs={
                'class': 'contnent__elem',
                'placeholder': 'Дата рождения'
            }),
            'Location': TextInput(attrs={
                'class': 'contnent__elem',
                'placeholder': 'Место жительства'
            }),
        }


class DiagnosisForm(ModelForm):
    class Meta:
        model = Diagnosis
        fields = ['Diagnos', 'Severity']

        widgets = {
            'Diagnos': TextInput(attrs={
                'class': 'contnent__elem',
                'placeholder': 'Диагноз'
            }),
            'Severity': TextInput(attrs={
                'class': 'contnent__elem',
                'placeholder': 'Степень тяжести'
            }),
        }

class TreatmentForm(ModelForm):
    class Meta:
        model = Treatment
        fields = ['MethodOfThreatment', 'DurationOfTreat']

        widgets = {
            'MethodOfThreatment': TextInput(attrs={
                'class': 'contnent__elem',
                'placeholder': 'Метод лечения'
            }),
            'DurationOfTreat': TextInput(attrs={
                'class': 'contnent__elem',
                'placeholder': 'Срок лечения'
            }),
        }

djangoOsvobojeniy/medicine/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.views.generic import DetailView, UpdateView
import datetime

# Create your views here.
def main(request):
    pacient = Pacient.objects.all()
    diagnosis = Diagnosis.objects.all()
    treatment = Treatment.objects.all()

    card = []

    for el1, el2, el3 in zip(pacient, diagnosis, treatment):
        card.append({'id': el1.id, 'name': el1.NamePac, 'diag': el2.Diagnos, 'treat': el3.MethodOfThreatment})

    return render(request, 'medicine/index.html',
                  {'pacient': pacient, 'treatment': treatment, 'diagnosis': diagnosis, 'card': card})


def create(request):
    if request.method == 'POST':
        pac = PacientForm(request.POST)
        dia = DiagnosisForm(request.POST)
        treat = TreatmentForm(request.POST)

        if pac.is_valid() and dia.is_valid() and treat.is_valid():
            pac.save()
            dia.save()
            treat.save()
            return redirect('home')
        else:
            error = "Неверно заполнены данные"

    pac = PacientForm()
    diag = DiagnosisForm()
    treat = TreatmentForm()
    error = ''

    data = {
        'pac': pac,
        'dia': diag,
        'treat': treat,
        'error': error
    }

    return render(request, 'medicine/edit.html', data)


class PacientInfoDetailView(DetailView):
    template_name = 'medicine/info.html'
    context_object_name = 'card'
    model = Pacient


def update(request, pk):
    try:
        pac = Pacient.objects.get(id=pk)
        dia = Diagnosis.objects.get(id=pk)
        treat = Treatment.objects.get(id=pk)

        if request.method == "POST":
            pac.NamePac = request.POST.get("NameOfPacietn")
            pac.Policy = request.POST.get("NumberOfPart")
            pac.Birth = request.POST.get("YearOfBirth")
            pac.Location = request.POST.get("LocationOfPac")

            dia.Diagnos = request.POST.get("DiseaseName")
            dia.Severity = request.POST.get("Severity")

            treat.MethodOfThreatment = request.POST.get("Treatment")
            treat.DurationOfTreat = request.POST.get("DurationOfTreat")


            pac.save()
            dia.save()
            treat.save()
            return redirect('home')
        else:
            return render(request, "medicine/update.html", {"pac": pac, "dia": dia, "treat": treat})
    except pac.DoesNotExist and dia.DoesNotExist and treat.DoesNotExist:
        return redirect("home")

def delete(request,pk):
    pac = Pacient.objects.get(id=pk)
    dia = Diagnosis.objects.get(id=pk)
    treat = Treatment.objects.get(id=pk)
    if request.method == 'POST':
        pac.delete()
        dia.delete()
        treat.delete()
        return redirect('home')
    else:
        return render(request, "medicine/delete.html", {"pac": pac})

djangoOsvobojeniy/medicine/templates/medicine/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <h1>Карточка пациента</h1>
</body>
</html>

djangoOsvobojeniy/medicine/templates/medicine/delete.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
     <link rel="stylesheet" href="{% static 'medicine/main.css' %}">
    <link rel="stylesheet" href=" {%  static 'medicine/reset.css' %} ">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">

    <title>Удаление пациета - {{ pac.NamePac }}</title>
</head>
<body>
    <div class="container">
        <div class="container_inner">
                <div class="content">
                    <div class="content_inner">
                        <form  method="post" >
                            {% csrf_token %}
                            <div class="main_content">
                                <h5>Вы собираетесь удалить карточку пациента - {{ pac.NamePac }}</h5>
                            </div>
                          <div class="content_button">
                                 <button class="button_submit" type="submit">Подтвердить удаление</button>
                            </div>
                        </form>
                    </div>
                </div>
        </div>
    </div>
</body>
</html>

djangoOsvobojeniy/medicine/templates/medicine/edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Форма добавления карточки пациента</title>
    <link rel="stylesheet" href="{% static 'medicine/main.css' %}">
    <link rel="stylesheet" href=" {%  static 'medicine/reset.css' %} ">
    <link rel="stylesheet" href=" {%  static 'medicine/form.css' %} ">

</head>
<body>
<form class="form__body" method="post" >
        {% csrf_token %}
		 <div class="form_wrap">
			  <div class="container">
					<div class="container__inner">
						 <div class="content">
                             <span>{{ error }}</span>
							  <div class="content__title">
									<h2>Основная информация о пациенте</h2>
							  </div>
							  <div class="border__content"></div>
							  <div class="main__content">
									<div class="main__content-elem">
										 {{ pac.NamePac }}
									</div>
									<div class="main__content-elem">
										 {{ pac.Policy }}
									</div>
									<div class="main__content-elem">
										{{ pac.Birth }}
									</div>
									<div class="main__content-elem">
                                        {{pac.Location}}
									</div>
							  </div>
							  <div class="content__title">
								<h2>Диагноз</h2>
						  		</div>
								<div class="border__content"></div>
								<div class="main__content">
									<div class="main__content-elem">
                                        {{dia.Diagnos}}
									</div>
									<div class="main__content-elem">
										{{ dia.Severity }}
									</div>
								</div>
								<div class="content__title">
									<h2>Лечение</h2>
									  </div>
									<div class="border__content"></div>
									<div class="main__content">
										<div class="main__content-elem">
                                            {{treat.MethodOfThreatment}}
										</div>
										<div class="main__content-elem">
											{{ treat.DurationOfTreat }}
                                        </div>

									</div>

							  <div class="border__content"></div>
							  <div class="footer__content">

									<div class="footer__content-elem">
										 <button type="submit" class="button__footer button__footet-singin" >Сохранить карточку пациента</button>
									</div>
							  </div>
						 </div>
					</div>
			  </div>
		 </div>
	</form>

</body>
</html>

djangoOsvobojeniy/medicine/templates/medicine/index.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'medicine/main.css' %}">
    <link rel="stylesheet" href=" {%  static 'medicine/reset.css' %} ">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">

    <title>Главная страница</title>
</head>
<body>
    <div class="container">
        <div class="container_inner">
            <div class="newPac">
                <input class="newPac_button" type="button" value="+" onclick="window.location.href='{% url 'New-pacient' %}'">
            </div>
            {% for el in card %}
                <div class="content">
                    <div class="content_inner">
                        <div class="main_content">
                             ФИО: {{ el.name }}
                        </div>
                        <div class="main_content">
                             Диагноз: {{ el.diag }}
                        </div>
                        <div class="main_content">
                            Способ лечения: {{ el.treat }}
                        </div>
                        <div class="content_button">
                            <input type="button" value="Подробнее"  onclick="window.location.href='{% url 'pacient-detail' el.id %} '">
                        </div>
                    </div>
                </div>

            {% endfor %}
        </div>
    </div>
</body>
</html>

djangoOsvobojeniy/medicine/templates/medicine/info.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
     <link rel="stylesheet" href="{% static 'medicine/main.css' %}">
    <link rel="stylesheet" href=" {%  static 'medicine/reset.css' %} ">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">

    <title>Карточка пациента - {{ card.NamePac }}</title>
</head>
<body>
    <div class="container">
        <div class="container_inner">
                <div class="content">
                    <div class="content_inner">
                        <div class="main_content">
                             ФИО: {{ card.NamePac }}
                        </div>
                        <div class="main_content">
                             Номер Полиса: {{ card.Policy}}
                        </div>
                        <div class="main_content">
                            Дата рождения: {{ card.Birth }}
                        </div>
                        <div class="main_content">
                            Место проживания: {{ card.Location }}
                        </div>
                       {% for el in card.diagnosis_set.all %}
                            <div class="main_content">
                                Диагноз: {{ el.Diagnos }}
                            </div>
                           <div class="main_content">
                                Степень тяжести: {{ el.Severity }}
                            </div>
                       {% endfor %}

                        {% for el in card.treatment_set.all %}
                            <div class="main_content">
                                Метод лечения: {{ el.MethodOfThreatment }}
                            </div>
                           <div class="main_content">
                                Время лечения: {{ el.DurationOfTreat }} дн.
                            </div>
                         {% endfor %}
                      <div class="content_button_info">
                            <input type="button" value="Вернуться на главную"  onclick="window.location.href='{% url 'home' %} '">
                            <input type="button" value="Измениить" onclick="window.location.href='{% url 'pacient-update' card.id %}'">
                            <input type="button" value="Удалить" onclick="window.location.href='{% url 'pacient-delete' card.id %}'">
                        </div>
                    </div>
                </div>
        </div>
    </div>
</body>
</html>

djangoOsvobojeniy/medicine/templates/medicine/update.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Изменение карточки пациента</title>
    <link rel="stylesheet" href="{% static 'medicine/main.css' %}">
    <link rel="stylesheet" href=" {%  static 'medicine/reset.css' %} ">
    <link rel="stylesheet" href=" {%  static 'medicine/form.css' %} ">
</head>
<body>
	<form id="form" class="form__body" method="post" >
          {% csrf_token %}
		 <div class="form_wrap">
			  <div class="container">
					<div class="container__inner">
						 <div class="content">
							  <div class="content__title">
									<h2>Основная информация о пациенте</h2>
							  </div>
							  <div class="border__content"></div>
							  <div class="main__content">
									<div class="main__content-elem">
										 <input type="text" class="contnent__elem" placeholder ="ФИО пациента" id ="NameOfPacietn" name="NameOfPacietn" value="{{ pac.NamePac }}" required>
									</div>
									<div class="main__content-elem">
										 <input type="text" class="contnent__elem form-control" placeholder ="№ старахового полиса" maxlength="9" id = "NumberOfPart" name="NumberOfPart" value="{{ pac.Policy }}" required>
									</div>
									<div class="main__content-elem">
										 <input type="text" class="contnent__elem" placeholder ="Дата рождения"  id = "YearOfBirth" name="YearOfBirth" value="{{ pac.Birth }}" required >
									</div>
									<div class="main__content-elem">
										 <input type="text" class="contnent__elem" placeholder ="Место жительства"  id = "LocationOfPac" name="LocationOfPac" value="{{ pac.Location }}"  required >
									</div>
							  </div>
							  <div class="content__title">
								<h2>Диагноз</h2>
						  		</div>
								<div class="border__content"></div>
								<div class="main__content">
									<div class="main__content-elem">
										<input type="text" class="contnent__elem" placeholder ="Название болезни" id = "DiseaseName" name= "DiseaseName" value="{{ dia.Diagnos }}" required >
									</div>
									<div class="main__content-elem">
										<input type="text" class="contnent__elem" placeholder ="Степень тяжести (если имеется)*" id = "Severity" name="Severity" value="{{ dia.Severity }}" required>
									</div>
								</div>
								<div class="content__title">
									<h2>Лечение</h2>
									  </div>
									<div class="border__content"></div>
									<div class="main__content">
										<div class="main__content-elem">
											<input type="text" class="contnent__elem" placeholder ="Характер лечения" id = "Treatment" name= "Treatment" value="{{ treat.MethodOfThreatment }}" required>
										</div>
										<div class="main__content-elem">
											<input type="text" class="contnent__elem" placeholder ="Срок лечения, в днях" id = "DurationOfTreat" name="DurationOfTreat" value="{{ treat.DurationOfTreat }}" required>
									</div>
							  <div class="border__content"></div>
							  <div class="footer__content">

									<div class="footer__content-elem">
										 <button type="submit" class="button__footer button__footet-singin" id ="send" name="send">Сохранить карточку пациента</button>
									</div>
							  </div>
						 </div>
					</div>
			  </div>
		 </div>
	</form>

</body>
</html>